sudo: required

services:
  - docker

language: generic

jobs:
  include:
    # Image build/push
    script:
      -  sh -c 'cd $(pwd)/images/nginx' && make build
    deploy:
      provider: script
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push
