sudo: required
dist: focal

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker pull amazonlinux:2

services:
- docker

language: go
go:
- 1.13.x


env:
  global:
  - REGISTRY=infoblox
  - IMGNAME=nginx-fips
  - PLATFORMS=amd64
  - ARCH=amd64
  - MULTI_ARCH_IMAGE=${REGISTRY}/nginx-fips-${ARCH}
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - secure: eTDRq224lR7726xiqa/Z6alNiSkJqVOkafKDe29luLAYkbaJH2i3VKtL5e8AXwD+FkGOR3H9XLlqGBpxDtgMol82LPuA2oXUHVXZmHf0a7cRLJACUSiOXgwijbwDRFiShaACc9dqKgYu+Zwli2JL/2lr+LFMaw3+wBJgG5D/5bhJYS5Hn2mPV0xYpdXMc3x9ayMCZBRkrGGqP9MQJLtuHM+ahyD3jMg8hwaOmMhK2lFPhqXp+ue6Dx+dDGL0bDFKDgrIc3fu3rA8LCBoeRMNH1pRELWLbZFu3/Z92gmeXaAl/OCD8yF4VH5NtHj7ht0sHQopma+RBKXSFKHumjuI2g1t9QZE4JZl7ubLiBE71rRwDJKOnJM1NMSJYV4M4k/IwI11Fqu9td1PC16C7mhIGdTp9yBWCs8AHpa6M5Jzjjw3h3PDZTPktjZ8J0Lc4PUgmWfigrABw7S4YpaQl0bgP/NGLxb102wJVkSrQmxRl44SttJSVhGAPcazX8oaRw0nm3JryuHZg6dvzem0/eFQRS2aJ/YoRA1Xplwz+Cc1KSpQpVRMeybk7nuBTZnBNnoBbIk1tpuVNlb4wLcn5WFR7ibzvm4Az9QXVKTvH3geeOzFWI9KZRUVghJ30+GNO/mNRIcE7VKdMHeCPKRDeRc3OCvu2dY+V9K152ET8sIIsJo=
  - secure: CGHsVr9H4+9p2l78U05JEGvz0iViLZZEVxlZH5xkCgJnhWMLd6btYsFOFnyRq4AD7PObp2QjFx/uzm6SAcjjv+zFU6kM5YzrrVNe5/Pfs6/ZVHNkUB4ij2nAQauZ13YtrZZlQ6x1/uD8yuIRN6etGsDDWnR+c7BCDrYWRaLAAZXtmMJQw7CAITtIJBop8P0j6rG5LH9RxPEHkf2bTA4WqBuMedC5ZrgtPIe2Pw71Urvf73HIM/f7hzk51yvLOLzGsjGbLPpP3p5NM9dCAnPrgOJDK30+YqsZGHKyYBnUaT1G3fKFODZu8TLmLC5KKIVtg9xfYJC+dB9B+MqbZHD1UONB2LdjSzlDqsvH4VX4PXM/zMvlh/m8LNiovW8u/hRfntuPpWyzTlKr/BlJWX9jAVzRsDdIx63Nn0s5ffNrXkx1s0Ol3DKKLLMQ5pTCZW+S5c5wLXLhCDe/wCA/Zzo+4aiUk1D2iP8SmjmIsygcaH8ALWaMeIHqBLLROkNqigMwNe65VmFo37DvS4wf4TGy8acrsnVPqdRKwNPCCafCpS7fNUyLU1H3zDfh5VOeliRgLkAY6Kap+H4z35PcvPKSr5qrIwW0TupSN0T5wMZ/7R2sFRfNaZ82kJAJZuU1U5UmtMPx3s0HCk2Pk12Koe8rOCM5+/zBbZEj44XreeY9oJg=
jobs:
  include:
    - script:
      - export MULTI_ARCH_IMG=${REGISTRY}/nginx-fips-${ARCH}
      - export TAG=nginx-v0.27.1
      - export PROJECT_DIR=${PWD}
      - cd ${PWD}/images/nginx/
      - make container 
      - cd ${PROJECT_DIR}
      - export BASEIMAGE=${REGISTRY}/nginx-fips:${TAG}
      - export TAG=v0.27.1
      - make test
      - make build && make build-plugin
      - make container
    - deploy:
        on:
          branch: 0.27.1-test-travis
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          && make push
